#fairchem -c puma_speed.yaml +run_dir_root=/path/to/run_dir

runner:
  _target_: fairchem.core.components.benchmark.uma_speed_benchmark.InferenceBenchRunner
  timeiters: 10
  natoms_list: [6000]
  model_checkpoints: {
    "uma_sm_cons": "/home/misko/checkpoints/uma_sm_130525.pt"
  }
  run_dir_root: ${run_dir_root}
  generate_traces: True
  # for large number atoms (ie: 1000+) turn off compile and turn on activation_checkpointing
  # for profiling, we substract the graph generation time by using external_graph_gen=True
  inference_settings:
    _target_: fairchem.core.units.mlip_unit.api.inference.InferenceSettings
    tf32: False
    activation_checkpointing: True
    merge_mole: True
    compile: False
    wigner_cuda: False
    external_graph_gen: True
    internal_graph_gen_version: 2